// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    FossBg: typeof import('./../src/components/foss-bg/index.vue')['default']
    HeaderSrcHeader: typeof import('./../src/components/Header/src/Header.vue')['default']
    IconSrcIcon: typeof import('./../src/components/Icon/src/Icon.vue')['default']
    LogoSrcLogo: typeof import('./../src/components/Logo/src/Logo.vue')['default']
    MenuSrcMenu: typeof import('./../src/components/Menu/src/Menu.vue')['default']
    TabMenuSrcTabMenu: typeof import('./../src/components/TabMenu/src/TabMenu.vue')['default']
  }
}

export { }
