// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    FossBg: typeof import('./../src/components/foss-bg/index.vue')['default']
    LogoSrcLogo: typeof import('./../src/components/Logo/src/Logo.vue')['default']
    Menu: typeof import('./../src/components/menu/index.vue')['default']
    TabMenuSrcTabMenu: typeof import('./../src/components/TabMenu/src/TabMenu.vue')['default']
  }
}

export { }
