// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonSrcButton: typeof import('./../src/components/Button/src/Button.vue')['default']
    EchartsSrcEcharts: typeof import('./../src/components/Echarts/src/Echarts.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    'ElForm\u02DD': typeof import('element-plus/es')['ElForm\u02DD']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElNumberInput: typeof import('element-plus/es')['ElNumberInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FossBg: typeof import('./../src/components/foss-bg/index.vue')['default']
    HeaderSrcHeader: typeof import('./../src/components/Header/src/Header.vue')['default']
    IconSrcIcon: typeof import('./../src/components/Icon/src/Icon.vue')['default']
    LogoSrcLogo: typeof import('./../src/components/Logo/src/Logo.vue')['default']
    MenuSrcMenu: typeof import('./../src/components/Menu/src/Menu.vue')['default']
    TabMenuSrcTabMenu: typeof import('./../src/components/TabMenu/src/TabMenu.vue')['default']
  }
}

export { }
